In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from datetime import datetime
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
f1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1600_accel_phone.txt',sep='[,,;]',engine='python')
f2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1601_accel_phone.txt',sep='[,,;]',engine='python')
f3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1602_accel_phone.txt',sep='[,,;]',engine='python')
f4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1603_accel_phone.txt',sep='[,,;]',engine='python')
f5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1604_accel_phone.txt',sep='[,,;]',engine='python')
f6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1605_accel_phone.txt',sep='[,,;]',engine='python')
f7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1606_accel_phone.txt',sep='[,,;]',engine='python')
f8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1607_accel_phone.txt',sep='[,,;]',engine='python')
f9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1608_accel_phone.txt',sep='[,,;]',engine='python')
f10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1609_accel_phone.txt',sep='[,,;]',engine='python')
f11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1610_accel_phone.txt',sep='[,,;]',engine='python')
f12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1611_accel_phone.txt',sep='[,,;]',engine='python')
f13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1612_accel_phone.txt',sep='[,,;]',engine='python')
f14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1613_accel_phone.txt',sep='[,,;]',engine='python')
f15=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1614_accel_phone.txt',sep='[,,;]',engine='python')
f16=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1615_accel_phone.txt',sep='[,,;]',engine='python')
f17=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1616_accel_phone.txt',sep='[,,;]',engine='python')
f18=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1617_accel_phone.txt',sep='[,,;]',engine='python')
f19=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1618_accel_phone.txt',sep='[,,;]',engine='python')
f20=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\accel\\data_1619_accel_phone.txt',sep='[,,;]',engine='python')
f1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f15.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f16.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f17.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f18.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f19.columns=['subject_id','activity_label','timestamp','x','y','z','m']
f20.columns=['subject_id','activity_label','timestamp','x','y','z','m']
ph_accel_tra=pd.concat([f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20],axis=0,sort=False)
label_name = ph_accel_tra['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
ph_accel_tra["activity_name"] = label_name


ph_accel_tra.columns=['subject_id','activity_label','timestamp','x_ph_accel','y_ph_accel','z_ph_accel','m',"activity_name"]
ph_accel_tra=ph_accel_tra.drop(['m'], axis = 1)
ph_accel_tra.head()

,subject_id,activity_label,timestamp,x_ph_accel,y_ph_accel,z_ph_accel,activity_name
0,1600,A,252207717164786,-0.879730,9.768784,1.016998,WALKING
1,1600,A,252207767518790,2.001495,11.109070,2.619156,WALKING
2,1600,A,252207817872794,0.450623,12.651642,0.184555,WALKING
3,1600,A,252207868226798,-2.164352,13.928436,-4.422485,WALKING
4,1600,A,252207918580802,-4.332779,13.361191,-0.718872,WALKING

In [3]:
ph_accel_tra.shape

(1580225, 7)

In [4]:
d1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1600_gyro_phone.txt',sep='[,,;]',engine='python')
d2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1601_gyro_phone.txt',sep='[,,;]',engine='python')
d3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1602_gyro_phone.txt',sep='[,,;]',engine='python')
d4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1603_gyro_phone.txt',sep='[,,;]',engine='python')
d5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1604_gyro_phone.txt',sep='[,,;]',engine='python')
d6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1605_gyro_phone.txt',sep='[,,;]',engine='python')
d7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1606_gyro_phone.txt',sep='[,,;]',engine='python')
d8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1607_gyro_phone.txt',sep='[,,;]',engine='python')
d9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1608_gyro_phone.txt',sep='[,,;]',engine='python')
d10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1609_gyro_phone.txt',sep='[,,;]',engine='python')
d11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1610_gyro_phone.txt',sep='[,,;]',engine='python')
d12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1611_gyro_phone.txt',sep='[,,;]',engine='python')
d13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1612_gyro_phone.txt',sep='[,,;]',engine='python')
d14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1613_gyro_phone.txt',sep='[,,;]',engine='python')
d15=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1614_gyro_phone.txt',sep='[,,;]',engine='python')
d16=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1615_gyro_phone.txt',sep='[,,;]',engine='python')
d17=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1616_gyro_phone.txt',sep='[,,;]',engine='python')
d18=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1617_gyro_phone.txt',sep='[,,;]',engine='python')
d19=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1618_gyro_phone.txt',sep='[,,;]',engine='python')
d20=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\phone\\gyro\\data_1619_gyro_phone.txt',sep='[,,;]',engine='python')
d1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d15.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d16.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d17.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d18.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d19.columns=['subject_id','activity_label','timestamp','x','y','z','m']
d20.columns=['subject_id','activity_label','timestamp','x','y','z','m']
ph_gyro_tra=pd.concat([d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20],axis=0,sort=False)
label_name = ph_gyro_tra['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
ph_gyro_tra["activity_name"] = label_name

ph_gyro_tra.columns=['subject_id','activity_label','timestamp','x_ph_gyro','y_ph_gyro','z_ph_gyro','m',"activity_name"]
ph_gyro_tra=ph_gyro_tra.drop(['m'], axis = 1)
ph_gyro_tra.head()

,subject_id,activity_label,timestamp,x_ph_gyro,y_ph_gyro,z_ph_gyro,activity_name
0,1600,A,252207968934806,-0.875137,0.015472,0.162231,WALKING
1,1600,A,252208019288809,-0.720169,0.388489,-0.284012,WALKING
2,1600,A,252208069642813,-0.571640,1.227402,-0.241669,WALKING
3,1600,A,252208119996817,-0.380493,1.202835,-0.213135,WALKING
4,1600,A,252208170350821,-0.225784,0.558136,0.124481,WALKING

In [5]:
ph_gyro_tra.shape

(1387292, 7)

In [6]:
a1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1600_accel_watch.txt',sep='[,,;]',engine='python')
a2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1601_accel_watch.txt',sep='[,,;]',engine='python')
a3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1602_accel_watch.txt',sep='[,,;]',engine='python')
a4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1603_accel_watch.txt',sep='[,,;]',engine='python')
a5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1604_accel_watch.txt',sep='[,,;]',engine='python')
a6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1605_accel_watch.txt',sep='[,,;]',engine='python')
a7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1606_accel_watch.txt',sep='[,,;]',engine='python')
a8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1607_accel_watch.txt',sep='[,,;]',engine='python')
a9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1608_accel_watch.txt',sep='[,,;]',engine='python')
a10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1609_accel_watch.txt',sep='[,,;]',engine='python')
a11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1610_accel_watch.txt',sep='[,,;]',engine='python')
a12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1611_accel_watch.txt',sep='[,,;]',engine='python')
a13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1612_accel_watch.txt',sep='[,,;]',engine='python')
a14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1613_accel_watch.txt',sep='[,,;]',engine='python')
a15=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1614_accel_watch.txt',sep='[,,;]',engine='python')
a16=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1615_accel_watch.txt',sep='[,,;]',engine='python')
a17=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1616_accel_watch.txt',sep='[,,;]',engine='python')
a18=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1617_accel_watch.txt',sep='[,,;]',engine='python')
a19=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1618_accel_watch.txt',sep='[,,;]',engine='python')
a20=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\accel\\data_1619_accel_watch.txt',sep='[,,;]',engine='python')
a1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a15.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a16.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a17.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a18.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a19.columns=['subject_id','activity_label','timestamp','x','y','z','m']
a20.columns=['subject_id','activity_label','timestamp','x','y','z','m']
wat_accel_tra=pd.concat([a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20],axis=0,sort=False)
label_name = wat_accel_tra['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
wat_accel_tra["activity_name"] = label_name

wat_accel_tra.columns=['subject_id','activity_label','timestamp','x_wt_accel','y_wt_accel','z_wt_accel','m',"activity_name"]
wat_accel_tra=wat_accel_tra.drop(['m'], axis = 1)
wat_accel_tra.head()

,subject_id,activity_label,timestamp,x_wt_accel,y_wt_accel,z_wt_accel,activity_name
0,1600,A,90426757696641,4.972757,-0.158317,6.696732,WALKING
1,1600,A,90426807196641,3.253720,-0.191835,6.107758,WALKING
2,1600,A,90426856696641,2.801216,-0.155922,5.997625,WALKING
3,1600,A,90426906196641,3.770868,-1.051354,7.731027,WALKING
4,1600,A,90426955696641,4.661511,0.169689,9.684695,WALKING

In [7]:
wat_accel_tra.shape

(1303995, 7)

In [8]:
s1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1600_gyro_watch.txt',sep='[,,;]',engine='python')
s2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1601_gyro_watch.txt',sep='[,,;]',engine='python')
s3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1602_gyro_watch.txt',sep='[,,;]',engine='python')
s4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1603_gyro_watch.txt',sep='[,,;]',engine='python')
s5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1604_gyro_watch.txt',sep='[,,;]',engine='python')
s6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1605_gyro_watch.txt',sep='[,,;]',engine='python')
s7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1606_gyro_watch.txt',sep='[,,;]',engine='python')
s8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1607_gyro_watch.txt',sep='[,,;]',engine='python')
s9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1608_gyro_watch.txt',sep='[,,;]',engine='python')
s10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1609_gyro_watch.txt',sep='[,,;]',engine='python')
s11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1610_gyro_watch.txt',sep='[,,;]',engine='python')
s12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1611_gyro_watch.txt',sep='[,,;]',engine='python')
s13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1612_gyro_watch.txt',sep='[,,;]',engine='python')
s14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1613_gyro_watch.txt',sep='[,,;]',engine='python')
s15=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1614_gyro_watch.txt',sep='[,,;]',engine='python')
s16=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1615_gyro_watch.txt',sep='[,,;]',engine='python')
s17=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1616_gyro_watch.txt',sep='[,,;]',engine='python')
s18=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1617_gyro_watch.txt',sep='[,,;]',engine='python')
s19=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1618_gyro_watch.txt',sep='[,,;]',engine='python')
s20=pd.read_csv('C:\\Users\\DELL1\\Desktop\\train\\watch\\gyro\\data_1619_gyro_watch.txt',sep='[,,;]',engine='python')
s1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s15.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s16.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s17.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s18.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s19.columns=['subject_id','activity_label','timestamp','x','y','z','m']
s20.columns=['subject_id','activity_label','timestamp','x','y','z','m']
wat_gyro_tra=pd.concat([s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20],axis=0,sort=False)
label_name = wat_gyro_tra['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
wat_gyro_tra["activity_name"] = label_name

wat_gyro_tra.columns=['subject_id','activity_label','timestamp','x_wt_gyro','y_wt_gyro','z_wt_gyro','m',"activity_name"]
wat_gyro_tra=wat_gyro_tra.drop(['m'], axis = 1)
wat_gyro_tra.head()

,subject_id,activity_label,timestamp,x_wt_gyro,y_wt_gyro,z_wt_gyro,activity_name
0,1600,A,90426807196641,0.387382,-0.618541,-0.048972,WALKING
1,1600,A,90426856696641,0.070999,-0.209480,-0.195978,WALKING
2,1600,A,90426906196641,0.037975,0.254976,-0.156563,WALKING
3,1600,A,90426955696641,0.073129,0.719431,-0.001035,WALKING
4,1600,A,90427005196641,-0.101574,1.082686,-0.134193,WALKING

In [9]:
wat_gyro_tra.shape

(1303418, 7)

In [10]:
train=pd.concat([ph_accel_tra,ph_gyro_tra,wat_accel_tra,wat_gyro_tra],axis=0,sort=False)
train.head()

,subject_id,activity_label,timestamp,x_ph_accel,y_ph_accel,z_ph_accel,activity_name,x_ph_gyro,y_ph_gyro,z_ph_gyro,x_wt_accel,y_wt_accel,z_wt_accel,x_wt_gyro,y_wt_gyro,z_wt_gyro
0,1600,A,252207717164786,-0.879730,9.768784,1.016998,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1600,A,252207767518790,2.001495,11.109070,2.619156,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1600,A,252207817872794,0.450623,12.651642,0.184555,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1600,A,252207868226798,-2.164352,13.928436,-4.422485,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1600,A,252207918580802,-4.332779,13.361191,-0.718872,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
train.tail()

,subject_id,activity_label,timestamp,x_ph_accel,y_ph_accel,z_ph_accel,activity_name,x_ph_gyro,y_ph_gyro,z_ph_gyro,x_wt_accel,y_wt_accel,z_wt_accel,x_wt_gyro,y_wt_gyro,z_wt_gyro
64827,1619,S,350830146796403,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,-1.051321,0.374564,0.203493
64828,1619,S,350830196752313,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,-1.363450,0.417187,0.263148
64829,1619,S,350830246708223,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,-1.190877,0.570585,0.314280
64830,1619,S,350830296664133,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,-0.356775,0.516256,0.253560
64831,1619,S,350830346620043,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,-0.049979,0.343683,0.067139

In [12]:
X_train = train.drop(["subject_id", "activity_label","timestamp", "activity_name"], axis = 1)
y_train = train["activity_label"]

In [13]:
from sklearn.preprocessing import Imputer
imp= Imputer(missing_values='NaN',strategy='mean',axis=0)
imp.fit(X_train)
X_train=imp.transform(X_train)
print(X_train[:10])

C:\Users\DELL1\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

[[-8.79730200e-01  9.76878400e+00  1.01699830e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [ 2.00149540e+00  1.11090700e+01  2.61915600e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [ 4.50622560e-01  1.26516420e+01  1.84555050e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-2.16435240e+00  1.39284360e+01 -4.42248540e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-4.33277900e+00  1.33611910e+01 -7.18872100e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-3.19442750e-01  1.33183590e+01 -2.32025150e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [ 1.56645200e+00  9.51527400e+00 -1.77764900e-02 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-3.23745730e-01  5.26266500e+00  3.22341920e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-1.81167600e+00  3.71051030e+00  1.37393190e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-1.13404850e+00  4.53826900e+00  2.29754640e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]]

In [14]:
X_train.shape

(5574930, 12)

In [15]:
q1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1620_accel_phone.txt',sep='[,,;]',engine='python')
q2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1621_accel_phone.txt',sep='[,,;]',engine='python')
q3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1622_accel_phone.txt',sep='[,,;]',engine='python')
q4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1623_accel_phone.txt',sep='[,,;]',engine='python')
q5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1624_accel_phone.txt',sep='[,,;]',engine='python')
q6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1625_accel_phone.txt',sep='[,,;]',engine='python')
q7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1626_accel_phone.txt',sep='[,,;]',engine='python')
q8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1627_accel_phone.txt',sep='[,,;]',engine='python')
q9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1628_accel_phone.txt',sep='[,,;]',engine='python')
q10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1629_accel_phone.txt',sep='[,,;]',engine='python')
q11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1630_accel_phone.txt',sep='[,,;]',engine='python')
q12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1631_accel_phone.txt',sep='[,,;]',engine='python')
q13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1632_accel_phone.txt',sep='[,,;]',engine='python')
q14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\accel\\data_1633_accel_phone.txt',sep='[,,;]',engine='python')
q1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
q14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
ph_accel_tes=pd.concat([q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14],axis=0,sort=False)
label_name = ph_accel_tes['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
ph_accel_tes["activity_name"] = label_name

ph_accel_tes.columns=['subject_id','activity_label','timestamp','x_ph_accel','y_ph_accel','z_ph_accel','m',"activity_name"]
ph_accel_tes=ph_accel_tes.drop(['m'], axis = 1)

ph_accel_tes.head()

,subject_id,activity_label,timestamp,x_ph_accel,y_ph_accel,z_ph_accel,activity_name
0,1620,A,938034700219921,9.979980,10.531952,-2.961151,WALKING
1,1620,A,938034717004589,7.232987,11.211700,-0.783981,WALKING
2,1620,A,938034767358593,6.013000,9.329330,-1.070175,WALKING
3,1620,A,938034784143261,5.563065,7.343353,-4.254425,WALKING
4,1620,A,938034834497265,4.485870,6.800384,-3.931946,WALKING

In [16]:
z1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1620_gyro_phone.txt',sep='[,,;]',engine='python')
z2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1621_gyro_phone.txt',sep='[,,;]',engine='python')
z3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1622_gyro_phone.txt',sep='[,,;]',engine='python')
z4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1623_gyro_phone.txt',sep='[,,;]',engine='python')
z5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1624_gyro_phone.txt',sep='[,,;]',engine='python')
z6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1625_gyro_phone.txt',sep='[,,;]',engine='python')
z7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1626_gyro_phone.txt',sep='[,,;]',engine='python')
z8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1627_gyro_phone.txt',sep='[,,;]',engine='python')
z9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1628_gyro_phone.txt',sep='[,,;]',engine='python')
z10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1629_gyro_phone.txt',sep='[,,;]',engine='python')
z11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1630_gyro_phone.txt',sep='[,,;]',engine='python')
z12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1631_gyro_phone.txt',sep='[,,;]',engine='python')
z13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1632_gyro_phone.txt',sep='[,,;]',engine='python')
z14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\phone\\gyro\\data_1633_gyro_phone.txt',sep='[,,;]',engine='python')
z1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
z14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
ph_gyro_tes=pd.concat([z1,z2,z3,z4,z5,z6,z7,z8,z9,z10,z11,z12,z13,z14],axis=0,sort=False)
label_name = ph_gyro_tes['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
ph_gyro_tes["activity_name"] = label_name

ph_gyro_tes.columns=['subject_id','activity_label','timestamp','x_ph_gyro','y_ph_gyro','z_ph_gyro','m',"activity_name"]
ph_gyro_tes=ph_gyro_tes.drop(['m'], axis = 1)

ph_gyro_tes.head()

,subject_id,activity_label,timestamp,x_ph_gyro,y_ph_gyro,z_ph_gyro,activity_name
0,1620,A,938035086267284,0.316513,0.900757,-0.928040,WALKING
1,1620,A,938035136621288,0.187683,0.590820,-0.176010,WALKING
2,1620,A,938035186975292,0.340454,0.755875,0.762848,WALKING
3,1620,A,938035237329296,0.475555,0.825500,0.109222,WALKING
4,1620,A,938035287683300,0.380371,0.595566,-0.035110,WALKING

In [17]:
w1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1620_accel_watch.txt',sep='[,,;]',engine='python')
w2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1621_accel_watch.txt',sep='[,,;]',engine='python')
w3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1622_accel_watch.txt',sep='[,,;]',engine='python')
w4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1623_accel_watch.txt',sep='[,,;]',engine='python')
w5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1624_accel_watch.txt',sep='[,,;]',engine='python')
w6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1625_accel_watch.txt',sep='[,,;]',engine='python')
w7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1626_accel_watch.txt',sep='[,,;]',engine='python')
w8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1627_accel_watch.txt',sep='[,,;]',engine='python')
w9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1628_accel_watch.txt',sep='[,,;]',engine='python')
w10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1629_accel_watch.txt',sep='[,,;]',engine='python')
w11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1630_accel_watch.txt',sep='[,,;]',engine='python')
w12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1631_accel_watch.txt',sep='[,,;]',engine='python')
w13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1632_accel_watch.txt',sep='[,,;]',engine='python')
w14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\accel\\data_1633_accel_watch.txt',sep='[,,;]',engine='python')
w1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
w14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
wat_accel_tes=pd.concat([w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,w14],axis=0,sort=False)
label_name = wat_accel_tes['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
wat_accel_tes["activity_name"] = label_name

wat_accel_tes.columns=['subject_id','activity_label','timestamp','x_wt_accel','y_wt_accel','z_wt_accel','m',"activity_name"]
wat_accel_tes=wat_accel_tes.drop(['m'], axis = 1)

wat_accel_tes.head()

,subject_id,activity_label,timestamp,x_wt_accel,y_wt_accel,z_wt_accel,activity_name
0,1620,A,37945671341814,5.423765,-6.936601,-4.954651,WALKING
1,1620,A,37945720841814,4.700716,-3.127426,-7.648128,WALKING
2,1620,A,37945770341814,8.033444,-4.700417,-5.024083,WALKING
3,1620,A,37945819841814,3.970484,-1.645415,-3.621080,WALKING
4,1620,A,37945869341814,5.689521,-0.584784,-5.313781,WALKING

In [18]:
wat_accel_tes.shape

(998266, 7)

In [19]:
x1=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1620_gyro_watch.txt',sep='[,,;]',engine='python')
x2=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1621_gyro_watch.txt',sep='[,,;]',engine='python')
x3=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1622_gyro_watch.txt',sep='[,,;]',engine='python')
x4=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1623_gyro_watch.txt',sep='[,,;]',engine='python')
x5=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1624_gyro_watch.txt',sep='[,,;]',engine='python')
x6=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1625_gyro_watch.txt',sep='[,,;]',engine='python')
x7=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1626_gyro_watch.txt',sep='[,,;]',engine='python')
x8=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1627_gyro_watch.txt',sep='[,,;]',engine='python')
x9=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1628_gyro_watch.txt',sep='[,,;]',engine='python')
x10=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1629_gyro_watch.txt',sep='[,,;]',engine='python')
x11=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1630_gyro_watch.txt',sep='[,,;]',engine='python')
x12=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1631_gyro_watch.txt',sep='[,,;]',engine='python')
x13=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1632_gyro_watch.txt',sep='[,,;]',engine='python')
x14=pd.read_csv('C:\\Users\\DELL1\\Desktop\\test\\watch\\gyro\\data_1633_gyro_watch.txt',sep='[,,;]',engine='python')
x1.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x2.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x3.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x4.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x5.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x6.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x7.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x8.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x9.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x10.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x11.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x12.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x13.columns=['subject_id','activity_label','timestamp','x','y','z','m']
x14.columns=['subject_id','activity_label','timestamp','x','y','z','m']
wat_gyro_tes=pd.concat([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14],axis=0,sort=False)
label_name = wat_gyro_tes['activity_label'].map({'A': "WALKING", 'B':"JOGGING", 'C':"STAIRS", 'D':"SITTING", 'E':"STANDING", 'F':"TYPING",'G':'BRUSHING TEETH','H':'EATING SOUP','I':'EATING CHIPS','J':'EATING PASTA','K':'DRINKING FROM CUP','L':'EATING SANDWICH','M':'KICKING','O':'PLAYING CATCH','P':'DRIBBLING','Q':'WRITING','R':'CLAPPING','S':'FOLDING CLOTH'})
wat_gyro_tes["activity_name"] = label_name

wat_gyro_tes.columns=['subject_id','activity_label','timestamp','x_wt_gyro','y_wt_gyro','z_wt_gyro','m',"activity_name"]
wat_gyro_tes=wat_gyro_tes.drop(['m'], axis = 1)

wat_gyro_tes.head()

,subject_id,activity_label,timestamp,x_wt_gyro,y_wt_gyro,z_wt_gyro,activity_name
0,1620,A,37945720841814,1.687799,-0.455597,-1.225795,WALKING
1,1620,A,37945770341814,-0.817703,1.180649,1.572655,WALKING
2,1620,A,37945819841814,-0.937013,0.248543,-0.132833,WALKING
3,1620,A,37945869341814,-2.319726,1.696237,2.558025,WALKING
4,1620,A,37945918841814,-2.654219,2.898921,1.020848,WALKING

In [20]:
test=pd.concat([ph_accel_tes,ph_gyro_tes,wat_accel_tes,wat_gyro_tes],axis=0,sort=False)
test.head()

,subject_id,activity_label,timestamp,x_ph_accel,y_ph_accel,z_ph_accel,activity_name,x_ph_gyro,y_ph_gyro,z_ph_gyro,x_wt_accel,y_wt_accel,z_wt_accel,x_wt_gyro,y_wt_gyro,z_wt_gyro
0,1620,A,938034700219921,9.979980,10.531952,-2.961151,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1620,A,938034717004589,7.232987,11.211700,-0.783981,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1620,A,938034767358593,6.013000,9.329330,-1.070175,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1620,A,938034784143261,5.563065,7.343353,-4.254425,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1620,A,938034834497265,4.485870,6.800384,-3.931946,WALKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
test.tail()

,subject_id,activity_label,timestamp,x_ph_accel,y_ph_accel,z_ph_accel,activity_name,x_ph_gyro,y_ph_gyro,z_ph_gyro,x_wt_accel,y_wt_accel,z_wt_accel,x_wt_gyro,y_wt_gyro,z_wt_gyro
64848,1633,S,697019338580377,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,-1.073295,-0.204933,-0.385017
64849,1633,S,697019388505837,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,0.467077,-0.545817,-0.487282
64850,1633,S,697019438431297,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,0.801570,-0.868592,-0.810057
64851,1633,S,697019488356757,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,1.715567,-1.226521,-1.232967
64852,1633,S,697019538282217,NaN,NaN,NaN,FOLDING CLOTH,NaN,NaN,NaN,NaN,NaN,NaN,1.811441,-1.753827,-1.964804

In [22]:
X_test = test.drop(["subject_id", "activity_label","timestamp", "activity_name"], axis = 1)
y_test = test["activity_label"]

In [23]:
from sklearn.preprocessing import Imputer
imp= Imputer(missing_values='NaN',strategy='mean',axis=0)
imp.fit(X_test)
X_test=imp.transform(X_test)
print(X_train[:10])
X_test.shape

C:\Users\DELL1\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

[[-8.79730200e-01  9.76878400e+00  1.01699830e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [ 2.00149540e+00  1.11090700e+01  2.61915600e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [ 4.50622560e-01  1.26516420e+01  1.84555050e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-2.16435240e+00  1.39284360e+01 -4.42248540e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-4.33277900e+00  1.33611910e+01 -7.18872100e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-3.19442750e-01  1.33183590e+01 -2.32025150e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [ 1.56645200e+00  9.51527400e+00 -1.77764900e-02 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-3.23745730e-01  5.26266500e+00  3.22341920e-01 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-1.81167600e+00  3.71051030e+00  1.37393190e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]
 [-1.13404850e+00  4.53826900e+00  2.29754640e+00 -3.58592280e-03
  -5.59817595e-03 -6.79022197e-03  6.86056657e-01 -4.82327644e+00
   2.15183025e+00 -2.88949665e-02 -2.04540491e-02  1.17617983e-02]]

(4266275, 12)

In [59]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train[:3600],y_train[:3600])
y_pred=knn.predict(X_test[:3600])
accuracy=(accuracy_score(y_test[:3600],y_pred[:3600]))*100
print('Accuracy is :' +str(accuracy)+'%')
print(confusion_matrix(y_test[:3600],y_pred[:3600]))
KNN_accuracy= str(accuracy)+'%'

Accuracy is :99.36111111111111%
[[3575    1]
 [  22    2]]

In [61]:
from sklearn.svm import SVC
svc=SVC(kernel='rbf')
svc.fit(X_train[:3600],y_train[:3600])
y_pred=svc.predict(X_test[:3600])
accuracy=(accuracy_score(y_test[:3600],y_pred[:3600]))*100
print('Accuracy is :' +str(accuracy)+'%')
print(confusion_matrix(y_test[:3600],y_pred[:3600]))
SVC_accuracy= str(accuracy)+'%'

Accuracy is :99.30555555555556%
[[3575    1]
 [  24    0]]

C:\Users\DELL1\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [62]:
logreg=LogisticRegression(multi_class='ovr')
logreg.fit(X_train[:3600],y_train[:3600])
y_pred=logreg.predict(X_test[:3600])
accuracy=(accuracy_score(y_test[:3600],y_pred[:3600]))*100
print('Accuracy is :' +str(accuracy)+'%')
print(confusion_matrix(y_test[:3600],y_pred[:3600]))
LOGREG_accuracy= str(accuracy)+'%'

Accuracy is :99.52777777777779%
[[3573    3]
 [  14   10]]

C:\Users\DELL1\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [63]:
dtc=DecisionTreeClassifier()
dtc.fit(X_train[:3600],y_train[:3600])
y_pred=dtc.predict(X_test[:3600])
accuracy=(accuracy_score(y_test[:3600],y_pred[:3600]))*100
print('Accuracy is :' +str(accuracy)+'%')
print(confusion_matrix(y_test[:3600],y_pred[:3600]))
DTC_accuracy= str(accuracy)+'%'

Accuracy is :83.02777777777777%
[[2967  609]
 [   2   22]]

In [64]:
rfc=RandomForestClassifier()
rfc.fit(X_train[:3600],y_train[:3600])
y_pred=rfc.predict(X_test[:3600])
accuracy=(accuracy_score(y_test[:3600],y_pred[:3600]))*100
print('Accuracy is :' +str(accuracy)+'%')
print(confusion_matrix(y_test[:3600],y_pred[:3600]))
RFC_accuracy= str(accuracy)+'%'

Accuracy is :97.19444444444446%
[[3486   90]
 [  11   13]]

C:\Users\DELL1\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [73]:
accuracy= pd.DataFrame({'Classifier':['KNeighborsClassifier','SVC','LogisticRegression','DecisionTreeClassifier','RandomForestClassifier'],'Accuracy':[KNN_accuracy,SVC_accuracy,LOGREG_accuracy,DTC_accuracy,RFC_accuracy]})
print(accuracy)

               Classifier            Accuracy
0    KNeighborsClassifier  99.36111111111111%
1                     SVC  99.30555555555556%
2      LogisticRegression  99.52777777777779%
3  DecisionTreeClassifier  83.02777777777777%
4  RandomForestClassifier  97.19444444444446%